[versions]
agp = "8.3.1"
appcompatVersion = "1.5.1"
compiler = "4.13.0"
compilerVersion = "4.12.0"
firebaseBom = "33.1.1"
firebaseUiDatabase = "8.0.2"
glide = "4.16.0"
glideVersion = "4.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
googleServices = "4.4.2"
firebaseAuth = "23.0.0"

[libraries]
appcompat-v151 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
compiler-v4120 = { module = "com.github.bumptech.glide:compiler", version.ref = "compilerVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-ui-database = { module = "com.firebaseui:firebase-ui-database", version.ref = "firebaseUiDatabase" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-v4120 = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

